!TCL=811, Sahi Narayan Raman
!TITLE=Sahi Keywords
!SORT=Y
!CHARSET=DEFAULT

!TEXT=_include
_include(URL/filePath)
!

!TEXT=_button
_button(id)
!

!TEXT=_submit
_submit(id)
!

!TEXT=_textbox
_textbox(id)
!

!TEXT=_password
_password(id)
!

!TEXT=_checkbox
_checkbox(id)
!

!TEXT=_textarea
_textarea(id)
!

!TEXT=_accessor
_accessor(id)
!

!TEXT=_byId
_byId(id)
!

!TEXT=_select
_select(id)
!

!TEXT=_radio
_radio(id)
!

!TEXT=_image
_image(id)
!

!TEXT=_imageSubmitButton
_imageSubmitButton(id)
!

!TEXT=_link
_link(id)
!

!TEXT=_getSelectedText
_getSelectedText(element)
!

!TEXT=_getCellText
_getCellText(element)
!

!TEXT=_random
_random()
!

!TEXT=_savedRandom
_savedRandom(id)
!

!TEXT=_cell
_cell(id)
!

!TEXT=_table
_table(id)
!

!TEXT=_containsHTML
_containsHTML(element,html)
!

!TEXT=_containsText
_containsText(element,txt)
!

!TEXT=_popup
_popup(id)
!

!TEXT=_event
_event
!

!TEXT=_click
_click(element)
!

!TEXT=_highlight
_highlight(element)
!

!TEXT=_setValue
_setValue(element, value)
!

!TEXT=_setSelected
_setSelected(element, selectedText)
!

!TEXT=_check
_check(element)
!

!TEXT=_wait
_wait(timeInMillis)
!

!TEXT=_simulateEvent
_simulateEvent(event)
!

!TEXT=_setGlobal
_setGlobal(name, value)
!

!TEXT=_getGlobal
_getGlobal(value)
!

!TEXT=_assertNotNull
_assertNotNull(element)
!

!TEXT=_assertNull
_assertNull(element)
!

!TEXT=_assertTrue
_assertTrue(condition)
!

!TEXT=_assertNotTrue
_assertNotTrue(condition)
!

!TEXT=_assertEqual
_assertEqual(object1, object2)
!

!TEXT=_assertNotEqual
_assertNotEqual(object1, object2)
!

!TEXT=_alert
_alert(txt);
!

!TEXT=_eval
_eval(commandString)
!

!TEXT=_call
_call(functionName)
!

!TEXT=_confirm
_confirm(txt)
!

!TEXT=_prompt
_prompt(txt)
!

!TEXT=_log
_log(txt)
!

!TEXT=_navigateTo
_navigateTo(url)
!

!TEXT=_row
_row(id)
!

!TEXT=_getText
_getText(element)
!

!TEXT=_div
_div(id)
!

!TEXT=_span
_span(id)
!

!TEXT=_spandiv
_spandiv(id)
!

!TEXT=_option
_option(id)
!

!TEXT=_lastConfirm
_lastConfirm()
!

!TEXT=_reset
_reset(id)
!

!TEXT=_file
_file(id)
!

!TEXT=_getDB
_getDB(driver, jdbcURL, username, password)
!

!TEXT=_readFile
_readFile(filePath)
!

!TEXT=_lastPrompt
_lastPrompt()
!

!TEXT=_lastAlert
_lastAlert()
!

!TEXT=_style
_style(element, styleAttribute)
!

!TEXT=_byText
_byText(txt, tagName)
!

!TEXT=_cookie
_cookie(name)
!

!TEXT=_position
_position(element)
!

!TEXT=_print
_print()
!

!TEXT=_printCalled
_printCalled()
!

!TEXT=_label
_label(id)
!

!TEXT=_lastDownloadedFileName
_lastDownloadedFileName()
!

!TEXT=_rteHTML
_rteHTML(element)
!

!TEXT=_rteText
_rteText(element)
!

!TEXT=_re
_re
!

!TEXT=_abbr
_abbr(id)
!

!TEXT=_activeElement
_activeElement()
!

!TEXT=_canvas
_canvas(id)
!

!TEXT=_dDesc
_dDesc(id)
!

!TEXT=_dList
_dList(id)
!

!TEXT=_dTerm
_dTerm(id)
!

!TEXT=_fieldset
_fieldset(id)
!

!TEXT=_font
_font(id)
!

!TEXT=_hidden
_hidden(id)
!

!TEXT=_byClassName
_byClassName(className)
!

!TEXT=_listItem
_listItem(id)
!

!TEXT=_list
_list(id)
!

!TEXT=_parentNode
_parentNode(element)
!

!TEXT=_parentCell
_parentCell(element)
!

!TEXT=_parentRow
_parentRow(element)
!

!TEXT=_parentTable
_parentTable(element)
!

!TEXT=_in
_in(element)
!

!TEXT=_near
_near(element)
!

!TEXT=_rte
_rte(id)
!

!TEXT=_iframe
_iframe(id)
!

!TEXT=_frame
_frame(id)
!

!TEXT=_tableHeader
_tableHeader(id)
!

!TEXT=_heading1
_heading1(id)
!

!TEXT=_heading2
_heading2(id)
!

!TEXT=_heading3
_heading3(id)
!

!TEXT=_heading4
_heading4(id)
!

!TEXT=_heading5
_heading5(id)
!

!TEXT=_heading6
_heading6(id)
!

!TEXT=_area
_area(id)
!

!TEXT=_map
_map(id)
!

!TEXT=_italic
_italic(id)
!

!TEXT=_bold
_bold(id)
!

!TEXT=_emphasis
_emphasis(id)
!

!TEXT=_strong
_strong(id)
!

!TEXT=_preformatted
_preformatted(id)
!

!TEXT=_code
_code(id)
!

!TEXT=_blockquote
_blockquote(id)
!

!TEXT=_xy
_xy(element, integer, integer)
!

!TEXT=_leftOf
_leftOf(element)
!

!TEXT=_leftOrRightOf
_leftOrRightOf(element)
!

!TEXT=_rightOf
_rightOf(element)
!

!TEXT=_under
_under(element)
!

!TEXT=_above
_above(element)
!

!TEXT=_aboveOrUnder
_aboveOrUnder(element)
!

!TEXT=_byXPath
_byXPath(xPath)
!

!TEXT=_bySeleniumLocator
_bySeleniumLocator(locatorString)
!

!TEXT=_getValue
_getValue(element)
!

!TEXT=_getAttribute
_getAttribute(element, attributeName)
!

!TEXT=_getSelectionText
_getSelectionText(element)
!

!TEXT=_hr
_hr(id)
!

!TEXT=_paragraph
_paragraph(id)
!

!TEXT=_isVisible
_isVisible(element)
!

!TEXT=_collect
_collect(apiType, id)
!

!TEXT=_count
_count(apiType, id)
!

!TEXT=_contains
_contains(parent, child)
!

!TEXT=_title
_title()
!

!TEXT=_exists
_exists(element)
!

!TEXT=_isIE
_isIE()
!

!TEXT=_isIE6
_isIE6()
!

!TEXT=_isIE7
_isIE7()
!

!TEXT=_isIE8
_isIE8()
!

!TEXT=_isIE11
_isIE11()
!

!TEXT=_isIE11Plus
_isIE11Plus()
!

!TEXT=_isIE9
_isIE9()
!

!TEXT=_isIE10
_isIE10()
!

!TEXT=_isFF
_isFF()
!

!TEXT=_isFF3
_isFF3()
!

!TEXT=_isFF4
_isFF4()
!

!TEXT=_isChrome
_isChrome()
!

!TEXT=_isSafari
_isSafari()
!

!TEXT=_isOpera
_isOpera()
!

!TEXT=_isHTMLUnit
_isHTMLUnit()
!

!TEXT=_fetch
_fetch(expression)
!

!TEXT=_readURL
_readURL(url)
!

!TEXT=_scriptName
_scriptName()
!

!TEXT=_logException
_logException(exception)
!

!TEXT=_logExceptionAsFailure
_logExceptionAsFailure(exception)
!

!TEXT=_stopOnError
_stopOnError()
!

!TEXT=_continueOnError
_continueOnError()
!

!TEXT=_scriptPath
_scriptPath()
!

!TEXT=_readCSVFile
_readCSVFile(filePath)
!

!TEXT=_writeFile
_writeFile(txt, filePath)
!

!TEXT=_writeToFile
_writeToFile(txt, filePath)
!

!TEXT=_deleteFile
_deleteFile(filePath)
!

!TEXT=_copyFile
_copyFile(srcFilePath, destFilePath)
!

!TEXT=_suiteInfo
_suiteInfo()
!

!TEXT=_writeCSVFile
_writeCSVFile(array2D, filePath)
!

!TEXT=_areEqualArrays
_areEqualArrays(array1, array2)
!

!TEXT=_userDataDir
_userDataDir()
!

!TEXT=_setRecovery
_setRecovery(function)
!

!TEXT=_removeRecovery
_removeRecovery()
!

!TEXT=_sessionInfo
_sessionInfo()
!

!TEXT=_renameFile
_renameFile(oldFilePath, newFilePath)
!

!TEXT=_runUnitTests
_runUnitTests()
!

!TEXT=_fail
_fail(txt)
!

!TEXT=_dataDrive
_dataDrive(function, array2D)
!

!TEXT=_condition
_condition(expression)
!

!TEXT=_setSpeed
_setSpeed(timeInMillis)
!

!TEXT=_selectWindow
_selectWindow(windowID)
!

!TEXT=_selectDomain
_selectDomain(domainID)
!

!TEXT=_userDataPath
_userDataPath(relativePath)
!

!TEXT=_evalOnRhino
_evalOnRhino()
!

!TEXT=_scriptStatus
_scriptStatus()
!

!TEXT=_scriptStartTime
_scriptStartTime()
!

!TEXT=_flex
_flex(id)
!

!TEXT=_stackTrace
_stackTrace()
!

!TEXT=_sendHTMLResponseAfterFileDownload
_sendHTMLResponseAfterFileDownload(true/false)
!

!TEXT=_dynamicInclude
_dynamicInclude(scriptPath)
!

!TEXT=_execute
_execute(command)
!

!TEXT=_resolvePath
_resolvePath(relativePath)
!

!TEXT=_datebox
_datebox(id)
!

!TEXT=_datetimebox
_datetimebox(id)
!

!TEXT=_datetimelocalbox
_datetimelocalbox(id)
!

!TEXT=_emailbox
_emailbox(id)
!

!TEXT=_monthbox
_monthbox(id)
!

!TEXT=_numberbox
_numberbox(id)
!

!TEXT=_rangebox
_rangebox(id)
!

!TEXT=_searchbox
_searchbox(id)
!

!TEXT=_telephonebox
_telephonebox(id)
!

!TEXT=_timebox
_timebox(id)
!

!TEXT=_urlbox
_urlbox(id)
!

!TEXT=_weekbox
_weekbox(id)
!

!TEXT=_testcase
_testcase(testcaseID, description)
!

!TEXT=_assert
_assert(condition, message)
!

!TEXT=_assertFalse
_assertFalse(condition, message)
!

!TEXT=_assertExists
_assertExists(element, message)
!

!TEXT=_assertNotExists
_assertNotExists(element, message)
!

!TEXT=_callServer
_callServer()
!

!TEXT=_clickLinkByAccessor
_clickLinkByAccessor()
!

!TEXT=_resetSavedRandom
_resetSavedRandom()
!

!TEXT=_doubleClick
_doubleClick(element)
!

!TEXT=_addMock
_addMock(string)
!

!TEXT=_removeMock
_removeMock(string)
!

!TEXT=_expectConfirm
_expectConfirm(message, true/false)
!

!TEXT=_setFile
_setFile(element, filePath)
!

!TEXT=_expectPrompt
_expectPrompt(string, string)
!

!TEXT=_debug
_debug(string)
!

!TEXT=_debugToErr
_debugToErr(string)
!

!TEXT=_debugToFile
_debugToFile(string, filePath)
!

!TEXT=_mouseOver
_mouseOver(element)
!

!TEXT=_keyPress
_keyPress(element, charInfo)
!

!TEXT=_focus
_focus(element)
!

!TEXT=_keyDown
_keyDown(element, charInfo)
!

!TEXT=_keyUp
_keyUp(element, charInfo)
!

!TEXT=_mockImage
_mockImage(string)
!

!TEXT=_assertContainsText
_assertContainsText(string, element, message)
!

!TEXT=_enableKeepAlive
_enableKeepAlive()
!

!TEXT=_disableKeepAlive
_disableKeepAlive()
!

!TEXT=_dragDropXY
_dragDropXY(element, integer, integer)
!

!TEXT=_deleteCookie
_deleteCookie(name)
!

!TEXT=_createCookie
_createCookie(name, value, expDays)
!

!TEXT=_saveDownloadedAs
_saveDownloadedAs(path)
!

!TEXT=_clearLastDownloadedFileName
_clearLastDownloadedFileName()
!

!TEXT=_rteWrite
_rteWrite(element, htmlString)
!

!TEXT=_assertEqualArrays
_assertEqualArrays(array1, array2, message)
!

!TEXT=_assertNotContainsText
_assertNotContainsText(string, element, message)
!

!TEXT=_blur
_blur(element)
!

!TEXT=_clearLastAlert
_clearLastAlert()
!

!TEXT=_clearLastConfirm
_clearLastConfirm()
!

!TEXT=_clearLastPrompt
_clearLastPrompt()
!

!TEXT=_clearPrintCalled
_clearPrintCalled()
!

!TEXT=_closeWindow
_closeWindow()
!

!TEXT=_domain
_domain(id)
!

!TEXT=_dragDrop
_dragDrop(dragElement, dropElement)
!

!TEXT=_mouseDown
_mouseDown(element, true/false)
!

!TEXT=_mouseUp
_mouseUp(element, true/false)
!

!TEXT=_removeFocus
_removeFocus()
!

!TEXT=_rightClick
_rightClick(element)
!

!TEXT=_simulateMouseEvent
_simulateMouseEvent()
!

!TEXT=_simulateMouseEventXY
_simulateMouseEventXY()
!

!TEXT=_type
_type(element, txt)
!

!TEXT=_uncheck
_uncheck(element)
!
