/*************************GO-LICENSE-START*********************************
 * Copyright 2015 ThoughtWorks, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *************************GO-LICENSE-END***********************************/

/* Auto generated by Twist. Please do not delete this file */

import com.thoughtworks.twist.core.execution.TwistScenarioDataStore;
import net.sf.sahi.client.Browser;
import org.springframework.beans.factory.annotation.Autowired;

/* Auto generated by Twist. Please do not delete this file */

/* Auto generated by Twist. Please do not delete this file */

public class ScenarioExecutionHooks {

	private Browser browser;

	@Autowired
	private TwistScenarioDataStore scenarioStore;

	public ScenarioExecutionHooks(Browser browser) {
		this.browser = browser;
	}

	@com.thoughtworks.gauge.BeforeStep
	public void beforeEachStep() throws Exception {
	
	}

	@com.thoughtworks.gauge.AfterStep
	public void afterEachStep() throws Exception {
	
	}

}